export {default as Apps} from '$components/icons/apps.svelte'
export {default as Briefcase} from '$components/icons/briefcase.svelte'
export {default as CheckboxCircle} from '$components/icons/checkbox-circle.svelte'
export {default as Chrome} from '$components/icons/chrome.svelte'
export {default as CodeBox} from '$components/icons/code-box.svelte'
export {default as Computer} from '$components/icons/computer.svelte'
export {default as Cpu} from '$components/icons/cpu.svelte'
export {default as ErrorWarning} from '$components/icons/error-warning.svelte'
export {default as FolderImage} from '$components/icons/folder-image.svelte'
export {default as FolderMusic} from '$components/icons/folder-music.svelte'
export {default as FolderVideo} from '$components/icons/folder-video.svelte'
export {default as FunctionAdd} from '$components/icons/function-add.svelte'
export {default as FundsBox} from '$components/icons/funds-box.svelte'
export {default as Gamepad} from '$components/icons/gamepad.svelte'
export {default as Github} from '$components/icons/github.svelte'
export {default as Global} from '$components/icons/global.svelte'
export {default as Home4} from '$components/icons/home-4.svelte'
export {default as InboxUnarchive} from '$components/icons/inbox-unarchive.svelte'
export {default as Information} from '$components/icons/information.svelte'
export {default as KeyboardBox} from '$components/icons/keyboard-box.svelte'
export {default as Message3} from '$components/icons/message-3.svelte'
export {default as Movie2} from '$components/icons/movie-2.svelte'
export {default as Questionnaire} from '$components/icons/questionnaire.svelte'
export {default as Search} from '$components/icons/search.svelte'
export {default as ShieldCross} from '$components/icons/shield-cross.svelte'

export { default as Icon } from '$components/icons/icon.svelte'